apiVersion: apps/v1
kind: Deployment
metadata:
  name: soldier-portal
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: soldier-portal
  template:
    metadata:
      labels:
        app: soldier-portal
    spec:
      containers:
      - image: docker.io/library/h2f-soldier-portal
        name: soldier-portal
        imagePullPolicy: IfNotPresent
        env:
          - name: PG_PW
            valueFrom:
              secretKeyRef:
                name: soldierportalsecrets
                key: PG_PW
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: soldierportalsecrets
                key: CLIENT_SECRET
          - name: SQLSERVER_PW
            valueFrom:
              secretKeyRef:
                name: soldierportalsecrets
                key: SQLSERVER_PW                
        envFrom:
        - configMapRef:
           name: configmap-soldier-portal        
        ports:
        - containerPort: 5001
